dist: trusty
sudo: required
language: node_js
node_js:
  - node

install:
  - npm i -g cordova ionic

before_script:
  - mkdir www

script:
  - npm run lint
  - npm run lint:css
  - cordova prepare
  - npm run build
